global:
  scrape_interval: 15s

scrape_configs:
  - job_name: krakend_otel
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'krakend:9091'  # Use the Docker Compose service name
        labels:
          app: kotel_example
          
